"""MCP response envelope (Charter v1.0).

Every MCP tool wraps its return value in a `ToolResponse[T]`:

    {
      "status": "success" | "empty" | "partial" | "degraded" | "error",
      "data": <T | None>,
      "error": <ToolError | None>,
      "confidence": "HIGH" | "MEDIUM" | "LOW" | None,
      "provenance": <Provenance | None>,
      "follow_up_hints": [<tool_name>, ...] | None,
      "charter_version": "1.0"
    }

The envelope is the public contract for Schema Brain's MCP surface. See
`docs/agent-ux-charter.md` for the full design rationale.

This module is intentionally free of FastMCP / transport concerns —
envelope construction must work in any context (tests, alternative
transports, in-process clients). The FastMCP wiring lives in
`server.py`.
"""

from __future__ import annotations

from typing import Any, Generic, Literal, TypeVar

from pydantic import BaseModel, ConfigDict, model_validator

# Pinned charter version. Bumped per the Versioning section of the
# charter; minor bumps are additive (new optional fields, new error
# kinds), major bumps remove or rename fields.
CHARTER_VERSION = "1.0"

Status = Literal["success", "empty", "partial", "degraded", "error"]
Confidence = Literal["HIGH", "MEDIUM", "LOW"]
ProvenanceSource = Literal["schema", "llm", "inferred"]
# v1.0 ships with seven kinds. Additions are minor-version bumps.
ErrorKind = Literal[
    "unknown_name",
    "malformed_name",
    "missing_credential",
    "index_not_ready",
    "schema_drift",
    "cost_cap_exceeded",
    "internal_error",
]

T = TypeVar("T")


class Provenance(BaseModel):
    """Per-response provenance annotation.

    `source="schema"` — facts came straight from the source database's
    information schema. No model field. `source="llm"` — generated by
    an LLM; `model` names which one. `source="inferred"` — derived from
    observed signals (query log, sampling); `observed_in` carries
    {count, first_seen, last_seen} or similar diagnostic metadata.
    """

    model_config = ConfigDict(frozen=True)

    source: ProvenanceSource
    model: str | None = None
    observed_in: dict[str, Any] | None = None


class Recovery(BaseModel):
    """Recovery hints — the agent's next move after an error.

    `suggested_tool` is the tool name to call next; `suggested_args` is
    the args dict to call it with. `fuzzy_matches` is a tuple of plausible
    alternatives — typically used for `unknown_name` errors where the
    caller's input was close to an existing entity. Stored as a tuple
    rather than a list so the frozen invariant survives caller-side
    in-place mutation attempts; JSON serialization is identical.
    """

    model_config = ConfigDict(frozen=True)

    suggested_tool: str | None = None
    suggested_args: dict[str, Any] | None = None
    fuzzy_matches: tuple[str, ...] = ()


class ToolError(BaseModel):
    """Structured error returned inside a `ToolResponse` with status='error'.

    `kind` is one of the seven registered kinds (charter v1.0). `message`
    is a single human-readable sentence. `recovery` carries the agent's
    next-move hint — never empty in practice, though `Recovery()` with
    no fields is structurally valid for kinds where no recovery exists.
    """

    model_config = ConfigDict(frozen=True)

    kind: ErrorKind
    message: str
    recovery: Recovery


class ToolResponse(BaseModel, Generic[T]):
    """The envelope every Schema Brain MCP tool returns.

    Invariants enforced by `_validate_status_data_invariant`:

    - `status="error"` requires `data is None` and a populated `error`.
    - Any other status requires `error is None`. `data` must be
      populated for `success`, may be an empty container for `empty`.
    """

    model_config = ConfigDict(frozen=True)

    status: Status
    data: T | None = None
    error: ToolError | None = None
    confidence: Confidence | None = None
    provenance: Provenance | None = None
    # Tuple (not list) so the frozen invariant survives caller-side
    # in-place mutation attempts. Pydantic coerces list input
    # transparently — call sites that pass `follow_up_hints=[...]`
    # don't need to change.
    follow_up_hints: tuple[str, ...] | None = None
    charter_version: str = CHARTER_VERSION

    @model_validator(mode="after")
    def _validate_status_data_invariant(self) -> ToolResponse[T]:
        if self.status == "error":
            if self.error is None:
                raise ValueError("status='error' requires an `error` object")
            if self.data is not None:
                raise ValueError("status='error' forbids non-None `data`")
            return self
        # Non-error path
        if self.error is not None:
            raise ValueError(f"status={self.status!r} forbids non-None `error`")
        if self.status == "success" and self.data is None:
            raise ValueError("status='success' requires `data` to be populated")
        return self


__all__ = [
    "CHARTER_VERSION",
    "Confidence",
    "ErrorKind",
    "Provenance",
    "ProvenanceSource",
    "Recovery",
    "Status",
    "ToolError",
    "ToolResponse",
]
